package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * KomentariSluzbaZamenik generated by hbm2java
 */
public class KomentariSluzbaZamenik  implements java.io.Serializable {


     private Integer idKom;
     private int idZamToSluzba;
     private String idMentor;
     private String komentar;

    public KomentariSluzbaZamenik() {
    }

	
    public KomentariSluzbaZamenik(int idZamToSluzba, String idMentor) {
        this.idZamToSluzba = idZamToSluzba;
        this.idMentor = idMentor;
    }
    public KomentariSluzbaZamenik(int idZamToSluzba, String idMentor, String komentar) {
       this.idZamToSluzba = idZamToSluzba;
       this.idMentor = idMentor;
       this.komentar = komentar;
    }
   
    public Integer getIdKom() {
        return this.idKom;
    }
    
    public void setIdKom(Integer idKom) {
        this.idKom = idKom;
    }
    public int getIdZamToSluzba() {
        return this.idZamToSluzba;
    }
    
    public void setIdZamToSluzba(int idZamToSluzba) {
        this.idZamToSluzba = idZamToSluzba;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


