package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * KomentariMentRuk generated by hbm2java
 */
public class KomentariMentRuk  implements java.io.Serializable {


     private Integer idKom;
     private int idMentToRuk;
     private String komentar;

    public KomentariMentRuk() {
    }

	
    public KomentariMentRuk(int idMentToRuk) {
        this.idMentToRuk = idMentToRuk;
    }
    public KomentariMentRuk(int idMentToRuk, String komentar) {
       this.idMentToRuk = idMentToRuk;
       this.komentar = komentar;
    }
   
    public Integer getIdKom() {
        return this.idKom;
    }
    
    public void setIdKom(Integer idKom) {
        this.idKom = idKom;
    }
    public int getIdMentToRuk() {
        return this.idMentToRuk;
    }
    
    public void setIdMentToRuk(int idMentToRuk) {
        this.idMentToRuk = idMentToRuk;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


