package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * KomentariStMent generated by hbm2java
 */
public class KomentariStMent  implements java.io.Serializable {


     private Integer idKomentar;
     private int idPrijava;
     private String idStudent;
     private String idMentor;
     private String komentar;

    public KomentariStMent() {
    }

	
    public KomentariStMent(int idPrijava, String idStudent, String idMentor) {
        this.idPrijava = idPrijava;
        this.idStudent = idStudent;
        this.idMentor = idMentor;
    }
    public KomentariStMent(int idPrijava, String idStudent, String idMentor, String komentar) {
       this.idPrijava = idPrijava;
       this.idStudent = idStudent;
       this.idMentor = idMentor;
       this.komentar = komentar;
    }
   
    public Integer getIdKomentar() {
        return this.idKomentar;
    }
    
    public void setIdKomentar(Integer idKomentar) {
        this.idKomentar = idKomentar;
    }
    public int getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(int idPrijava) {
        this.idPrijava = idPrijava;
    }
    public String getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(String idStudent) {
        this.idStudent = idStudent;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


