package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * KomentariSluzbaStudentz generated by hbm2java
 */
public class KomentariSluzbaStudentz  implements java.io.Serializable {


     private Integer idKom;
     private int idZamToSluzba;
     private String idStudent;
     private String komentar;

    public KomentariSluzbaStudentz() {
    }

	
    public KomentariSluzbaStudentz(int idZamToSluzba, String idStudent) {
        this.idZamToSluzba = idZamToSluzba;
        this.idStudent = idStudent;
    }
    public KomentariSluzbaStudentz(int idZamToSluzba, String idStudent, String komentar) {
       this.idZamToSluzba = idZamToSluzba;
       this.idStudent = idStudent;
       this.komentar = komentar;
    }
   
    public Integer getIdKom() {
        return this.idKom;
    }
    
    public void setIdKom(Integer idKom) {
        this.idKom = idKom;
    }
    public int getIdZamToSluzba() {
        return this.idZamToSluzba;
    }
    
    public void setIdZamToSluzba(int idZamToSluzba) {
        this.idZamToSluzba = idZamToSluzba;
    }
    public String getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(String idStudent) {
        this.idStudent = idStudent;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


