package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * KomentariMentZam generated by hbm2java
 */
public class KomentariMentZam  implements java.io.Serializable {


     private Integer idKom;
     private int idMentToZam;
     private String komentar;

    public KomentariMentZam() {
    }

	
    public KomentariMentZam(int idMentToZam) {
        this.idMentToZam = idMentToZam;
    }
    public KomentariMentZam(int idMentToZam, String komentar) {
       this.idMentToZam = idMentToZam;
       this.komentar = komentar;
    }
   
    public Integer getIdKom() {
        return this.idKom;
    }
    
    public void setIdKom(Integer idKom) {
        this.idKom = idKom;
    }
    public int getIdMentToZam() {
        return this.idMentToZam;
    }
    
    public void setIdMentToZam(int idMentToZam) {
        this.idMentToZam = idMentToZam;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


