package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * KomentariSluzbaMentor generated by hbm2java
 */
public class KomentariSluzbaMentor  implements java.io.Serializable {


     private Integer idKom;
     private Integer idRukToSluzba;
     private Integer idZamToSluzba;
     private String idMentor;
     private String komentar;

    public KomentariSluzbaMentor() {
    }

	
    public KomentariSluzbaMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public KomentariSluzbaMentor(Integer idRukToSluzba, Integer idZamToSluzba, String idMentor, String komentar) {
       this.idRukToSluzba = idRukToSluzba;
       this.idZamToSluzba = idZamToSluzba;
       this.idMentor = idMentor;
       this.komentar = komentar;
    }
   
    public Integer getIdKom() {
        return this.idKom;
    }
    
    public void setIdKom(Integer idKom) {
        this.idKom = idKom;
    }
    public Integer getIdRukToSluzba() {
        return this.idRukToSluzba;
    }
    
    public void setIdRukToSluzba(Integer idRukToSluzba) {
        this.idRukToSluzba = idRukToSluzba;
    }
    public Integer getIdZamToSluzba() {
        return this.idZamToSluzba;
    }
    
    public void setIdZamToSluzba(Integer idZamToSluzba) {
        this.idZamToSluzba = idZamToSluzba;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


