package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * KomentariSluzbaStudent generated by hbm2java
 */
public class KomentariSluzbaStudent  implements java.io.Serializable {


     private Integer idKom;
     private int idRukToSluzba;
     private String idStudent;
     private String komentar;

    public KomentariSluzbaStudent() {
    }

	
    public KomentariSluzbaStudent(int idRukToSluzba, String idStudent) {
        this.idRukToSluzba = idRukToSluzba;
        this.idStudent = idStudent;
    }
    public KomentariSluzbaStudent(int idRukToSluzba, String idStudent, String komentar) {
       this.idRukToSluzba = idRukToSluzba;
       this.idStudent = idStudent;
       this.komentar = komentar;
    }
   
    public Integer getIdKom() {
        return this.idKom;
    }
    
    public void setIdKom(Integer idKom) {
        this.idKom = idKom;
    }
    public int getIdRukToSluzba() {
        return this.idRukToSluzba;
    }
    
    public void setIdRukToSluzba(int idRukToSluzba) {
        this.idRukToSluzba = idRukToSluzba;
    }
    public String getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(String idStudent) {
        this.idStudent = idStudent;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


