package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private String username;
     private String ime;
     private String prezime;
     private String EMail;
     private String password;

    public Korisnik() {
    }

	
    public Korisnik(String username, String EMail, String password) {
        this.username = username;
        this.EMail = EMail;
        this.password = password;
    }
    public Korisnik(String username, String ime, String prezime, String EMail, String password) {
       this.username = username;
       this.ime = ime;
       this.prezime = prezime;
       this.EMail = EMail;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


