package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Masterrad generated by hbm2java
 */
public class Masterrad  implements java.io.Serializable {


     private Integer idRad;
     private String nazivS;
     private String nazivE;
     private String predmet;
     private String sadrzaj;

    public Masterrad() {
    }

	
    public Masterrad(String nazivS, String nazivE) {
        this.nazivS = nazivS;
        this.nazivE = nazivE;
    }
    public Masterrad(String nazivS, String nazivE, String predmet, String sadrzaj) {
       this.nazivS = nazivS;
       this.nazivE = nazivE;
       this.predmet = predmet;
       this.sadrzaj = sadrzaj;
    }
   
    public Integer getIdRad() {
        return this.idRad;
    }
    
    public void setIdRad(Integer idRad) {
        this.idRad = idRad;
    }
    public String getNazivS() {
        return this.nazivS;
    }
    
    public void setNazivS(String nazivS) {
        this.nazivS = nazivS;
    }
    public String getNazivE() {
        return this.nazivE;
    }
    
    public void setNazivE(String nazivE) {
        this.nazivE = nazivE;
    }
    public String getPredmet() {
        return this.predmet;
    }
    
    public void setPredmet(String predmet) {
        this.predmet = predmet;
    }
    public String getSadrzaj() {
        return this.sadrzaj;
    }
    
    public void setSadrzaj(String sadrzaj) {
        this.sadrzaj = sadrzaj;
    }




}


