package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Mentor generated by hbm2java
 */
public class Mentor  implements java.io.Serializable {


     private String username;

    public Mentor() {
    }

    public Mentor(String username) {
       this.username = username;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


