package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Menttoruk generated by hbm2java
 */
public class Menttoruk  implements java.io.Serializable {


     private Integer idMentToRuk;
     private int idPrijava;
     private String idMentor;
     private String idRuk;
     private Integer status;

    public Menttoruk() {
    }

	
    public Menttoruk(int idPrijava, String idMentor, String idRuk) {
        this.idPrijava = idPrijava;
        this.idMentor = idMentor;
        this.idRuk = idRuk;
    }
    public Menttoruk(int idPrijava, String idMentor, String idRuk, Integer status) {
       this.idPrijava = idPrijava;
       this.idMentor = idMentor;
       this.idRuk = idRuk;
       this.status = status;
    }
   
    public Integer getIdMentToRuk() {
        return this.idMentToRuk;
    }
    
    public void setIdMentToRuk(Integer idMentToRuk) {
        this.idMentToRuk = idMentToRuk;
    }
    public int getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(int idPrijava) {
        this.idPrijava = idPrijava;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getIdRuk() {
        return this.idRuk;
    }
    
    public void setIdRuk(String idRuk) {
        this.idRuk = idRuk;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


