package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Menttozam generated by hbm2java
 */
public class Menttozam  implements java.io.Serializable {


     private Integer idMentToZam;
     private int idPrijava;
     private String idMentor;
     private String idZam;
     private Integer status;

    public Menttozam() {
    }

	
    public Menttozam(int idPrijava, String idMentor, String idZam) {
        this.idPrijava = idPrijava;
        this.idMentor = idMentor;
        this.idZam = idZam;
    }
    public Menttozam(int idPrijava, String idMentor, String idZam, Integer status) {
       this.idPrijava = idPrijava;
       this.idMentor = idMentor;
       this.idZam = idZam;
       this.status = status;
    }
   
    public Integer getIdMentToZam() {
        return this.idMentToZam;
    }
    
    public void setIdMentToZam(Integer idMentToZam) {
        this.idMentToZam = idMentToZam;
    }
    public int getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(int idPrijava) {
        this.idPrijava = idPrijava;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getIdZam() {
        return this.idZam;
    }
    
    public void setIdZam(String idZam) {
        this.idZam = idZam;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


