package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Modul generated by hbm2java
 */
public class Modul  implements java.io.Serializable {


     private int idModul;
     private String naziv;

    public Modul() {
    }

    public Modul(int idModul, String naziv) {
       this.idModul = idModul;
       this.naziv = naziv;
    }
   
    public int getIdModul() {
        return this.idModul;
    }
    
    public void setIdModul(int idModul) {
        this.idModul = idModul;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }




}


