package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Pozicija generated by hbm2java
 */
public class Pozicija  implements java.io.Serializable {


     private int idPoz;
     private String pozicija;

    public Pozicija() {
    }

    public Pozicija(int idPoz, String pozicija) {
       this.idPoz = idPoz;
       this.pozicija = pozicija;
    }
   
    public int getIdPoz() {
        return this.idPoz;
    }
    
    public void setIdPoz(int idPoz) {
        this.idPoz = idPoz;
    }
    public String getPozicija() {
        return this.pozicija;
    }
    
    public void setPozicija(String pozicija) {
        this.pozicija = pozicija;
    }




}


