package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Predmet generated by hbm2java
 */
public class Predmet  implements java.io.Serializable {


     private Integer idPredmet;
     private int idModul;
     private String naziv;
     private int esbp;
     private String sifra;

    public Predmet() {
    }

    public Predmet(int idModul, String naziv, int esbp, String sifra) {
       this.idModul = idModul;
       this.naziv = naziv;
       this.esbp = esbp;
       this.sifra = sifra;
    }
   
    public Integer getIdPredmet() {
        return this.idPredmet;
    }
    
    public void setIdPredmet(Integer idPredmet) {
        this.idPredmet = idPredmet;
    }
    public int getIdModul() {
        return this.idModul;
    }
    
    public void setIdModul(int idModul) {
        this.idModul = idModul;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public int getEsbp() {
        return this.esbp;
    }
    
    public void setEsbp(int esbp) {
        this.esbp = esbp;
    }
    public String getSifra() {
        return this.sifra;
    }
    
    public void setSifra(String sifra) {
        this.sifra = sifra;
    }




}


