package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Predaje generated by hbm2java
 */
public class Predaje  implements java.io.Serializable {


     private Integer idPredaje;
     private String idMentor;
     private String idStudent;
     private int idPredmet;

    public Predaje() {
    }

    public Predaje(String idMentor, String idStudent, int idPredmet) {
       this.idMentor = idMentor;
       this.idStudent = idStudent;
       this.idPredmet = idPredmet;
    }
   
    public Integer getIdPredaje() {
        return this.idPredaje;
    }
    
    public void setIdPredaje(Integer idPredaje) {
        this.idPredaje = idPredaje;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(String idStudent) {
        this.idStudent = idStudent;
    }
    public int getIdPredmet() {
        return this.idPredmet;
    }
    
    public void setIdPredmet(int idPredmet) {
        this.idPredmet = idPredmet;
    }




}


