package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prijava generated by hbm2java
 */
public class Prijava  implements java.io.Serializable {


     private Integer idPrijava;
     private String idStudent;
     private String idMentor;
     private String idMentorZ;
     private String idRukovodilac;
     private int idRad;
     private Integer idPredmet;
     private int rukIliProf;
     private String biografija;
     private String idRukRada;
     private String idKom1;
     private String idKom2;
     private Date datum;
     private Integer prihvata;
     private String sugestija;
     private Date datumS;
     private String predsednikKomisije;
     private int imaGreske;
     private int prijavljena;

    public Prijava() {
    }


	
      
        public Prijava(String idStudent, String idMentor, String idRukovodilac, int idRad, Integer idPredmet, int rukIliProf, String biografija, int imaGreske, int prijavljena) {
       this.idStudent = idStudent;
       this.idMentor = idMentor;
       this.idRad = idRad;
       this.idPredmet = idPredmet;
       this.rukIliProf = rukIliProf;
       this.biografija = biografija;
       this.imaGreske = imaGreske;
       this.prijavljena = prijavljena;
        this.idRukovodilac = idRukovodilac;
    }
   
     public Prijava(String idStudent, String idMentor, String idRukovodilac, Integer idPredmet, int rukIliProf, int imaGreske) {
       this.idStudent = idStudent;
       this.idMentor = idMentor;
       this.idRad = 0;
       this.idPredmet = idPredmet;
       this.rukIliProf = rukIliProf;
       this.biografija = null;
       this.imaGreske = imaGreske;
       this.prijavljena = 0;
	   
        this.idRukovodilac = idRukovodilac;
    }
    public Prijava(String idStudent, String idMentor,String idRukovodilac, int idRad, Integer idPredmet, int rukIliProf, String biografija, String idRukRada, String idKom1, String idKom2, Date datum, int imaGreske, int prijavljena) {
       this.idStudent = idStudent;
       this.idMentor = idMentor;
       this.idRad = idRad;
       this.idPredmet = idPredmet;
       this.rukIliProf = rukIliProf;
       this.biografija = biografija;
       this.idRukRada = idRukRada;
       this.idKom1 = idKom1;
       this.idKom2 = idKom2;
       this.datum = datum;
       this.imaGreske = imaGreske;
       this.prijavljena = prijavljena;
        this.idRukovodilac = idRukovodilac;
    }
    public Prijava(String idStudent, String idMentor, String idMentorZ, String idRukovodilac, int idRad, Integer idPredmet, int rukIliProf, String biografija, String idRukRada, String idKom1, String idKom2, Date datum, Integer prihvata, String sugestija, Date datumS, String predsednikKomisije, int imaGreske, int prijavljena) {
       this.idStudent = idStudent;
       this.idMentor = idMentor;
       this.idMentorZ = idMentorZ;
       this.idRukovodilac = idRukovodilac;
       this.idRad = idRad;
       this.idPredmet = idPredmet;
       this.rukIliProf = rukIliProf;
       this.biografija = biografija;
       this.idRukRada = idRukRada;
       this.idKom1 = idKom1;
       this.idKom2 = idKom2;
       this.datum = datum;
       this.prihvata = prihvata;
       this.sugestija = sugestija;
       this.datumS = datumS;
       this.predsednikKomisije = predsednikKomisije;
       this.imaGreske = imaGreske;
       this.prijavljena = prijavljena;
    }
   
    public Integer getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(Integer idPrijava) {
        this.idPrijava = idPrijava;
    }
    public String getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(String idStudent) {
        this.idStudent = idStudent;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getIdMentorZ() {
        return this.idMentorZ;
    }
    
    public void setIdMentorZ(String idMentorZ) {
        this.idMentorZ = idMentorZ;
    }
    public String getIdRukovodilac() {
        return this.idRukovodilac;
    }
    
    public void setIdRukovodilac(String idRukovodilac) {
        this.idRukovodilac = idRukovodilac;
    }
    public int getIdRad() {
        return this.idRad;
    }
    
    public void setIdRad(int idRad) {
        this.idRad = idRad;
    }
    public Integer getIdPredmet() {
        return this.idPredmet;
    }
    
    public void setIdPredmet(Integer idPredmet) {
        this.idPredmet = idPredmet;
    }
    public int getRukIliProf() {
        return this.rukIliProf;
    }
    
    public void setRukIliProf(int rukIliProf) {
        this.rukIliProf = rukIliProf;
    }
    public String getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(String biografija) {
        this.biografija = biografija;
    }
    public String getIdRukRada() {
        return this.idRukRada;
    }
    
    public void setIdRukRada(String idRukRada) {
        this.idRukRada = idRukRada;
    }
    public String getIdKom1() {
        return this.idKom1;
    }
    
    public void setIdKom1(String idKom1) {
        this.idKom1 = idKom1;
    }
    public String getIdKom2() {
        return this.idKom2;
    }
    
    public void setIdKom2(String idKom2) {
        this.idKom2 = idKom2;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Integer getPrihvata() {
        return this.prihvata;
    }
    
    public void setPrihvata(Integer prihvata) {
        this.prihvata = prihvata;
    }
    public String getSugestija() {
        return this.sugestija;
    }
    
    public void setSugestija(String sugestija) {
        this.sugestija = sugestija;
    }
    public Date getDatumS() {
        return this.datumS;
    }
    
    public void setDatumS(Date datumS) {
        this.datumS = datumS;
    }
    public String getPredsednikKomisije() {
        return this.predsednikKomisije;
    }
    
    public void setPredsednikKomisije(String predsednikKomisije) {
        this.predsednikKomisije = predsednikKomisije;
    }
    public int getImaGreske() {
        return this.imaGreske;
    }
    
    public void setImaGreske(int imaGreske) {
        this.imaGreske = imaGreske;
    }
    public int getPrijavljena() {
        return this.prijavljena;
    }
    
    public void setPrijavljena(int prijavljena) {
        this.prijavljena = prijavljena;
    }




}


