package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * RukovodilacModula generated by hbm2java
 */
public class RukovodilacModula  implements java.io.Serializable {


     private String username;
     private String usernameZ;
     private int idModul;
     private int sprecen;

    public RukovodilacModula() {
    }

	
    public RukovodilacModula(String username, int idModul, int sprecen) {
        this.username = username;
        this.idModul = idModul;
        this.sprecen = sprecen;
    }
    public RukovodilacModula(String username, String usernameZ, int idModul, int sprecen) {
       this.username = username;
       this.usernameZ = usernameZ;
       this.idModul = idModul;
       this.sprecen = sprecen;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUsernameZ() {
        return this.usernameZ;
    }
    
    public void setUsernameZ(String usernameZ) {
        this.usernameZ = usernameZ;
    }
    public int getIdModul() {
        return this.idModul;
    }
    
    public void setIdModul(int idModul) {
        this.idModul = idModul;
    }
    public int getSprecen() {
        return this.sprecen;
    }
    
    public void setSprecen(int sprecen) {
        this.sprecen = sprecen;
    }




}


