package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Ruktosluzba generated by hbm2java
 */
public class Ruktosluzba  implements java.io.Serializable {


     private Integer idRukToSluzba;
     private int idMentToRuk;
     private String idRuk;
     private String idSluzba;
     private Integer status;

    public Ruktosluzba() {
    }

	
    public Ruktosluzba(int idMentToRuk, String idRuk, String idSluzba) {
        this.idMentToRuk = idMentToRuk;
        this.idRuk = idRuk;
        this.idSluzba = idSluzba;
    }
    public Ruktosluzba(int idMentToRuk, String idRuk, String idSluzba, Integer status) {
       this.idMentToRuk = idMentToRuk;
       this.idRuk = idRuk;
       this.idSluzba = idSluzba;
       this.status = status;
    }
   
    public Integer getIdRukToSluzba() {
        return this.idRukToSluzba;
    }
    
    public void setIdRukToSluzba(Integer idRukToSluzba) {
        this.idRukToSluzba = idRukToSluzba;
    }
    public int getIdMentToRuk() {
        return this.idMentToRuk;
    }
    
    public void setIdMentToRuk(int idMentToRuk) {
        this.idMentToRuk = idMentToRuk;
    }
    public String getIdRuk() {
        return this.idRuk;
    }
    
    public void setIdRuk(String idRuk) {
        this.idRuk = idRuk;
    }
    public String getIdSluzba() {
        return this.idSluzba;
    }
    
    public void setIdSluzba(String idSluzba) {
        this.idSluzba = idSluzba;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


