package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sastanak generated by hbm2java
 */
public class Sastanak  implements java.io.Serializable {


     private Integer idSastanak;
     private String idSluzba;
     private String idUprava1;
     private String idUprava2;
     private int idPrijava;
     private Date datum;
     private int odrzan;

    public Sastanak() {
    }

    public Sastanak(String idSluzba, String idUprava1, String idUprava2, int idPrijava, Date datum, int odrzan) {
       this.idSluzba = idSluzba;
       this.idUprava1 = idUprava1;
       this.idUprava2 = idUprava2;
       this.idPrijava = idPrijava;
       this.datum = datum;
       this.odrzan = odrzan;
    }
   
    public Integer getIdSastanak() {
        return this.idSastanak;
    }
    
    public void setIdSastanak(Integer idSastanak) {
        this.idSastanak = idSastanak;
    }
    public String getIdSluzba() {
        return this.idSluzba;
    }
    
    public void setIdSluzba(String idSluzba) {
        this.idSluzba = idSluzba;
    }
    public String getIdUprava1() {
        return this.idUprava1;
    }
    
    public void setIdUprava1(String idUprava1) {
        this.idUprava1 = idUprava1;
    }
    public String getIdUprava2() {
        return this.idUprava2;
    }
    
    public void setIdUprava2(String idUprava2) {
        this.idUprava2 = idUprava2;
    }
    public int getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(int idPrijava) {
        this.idPrijava = idPrijava;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public int getOdrzan() {
        return this.odrzan;
    }
    
    public void setOdrzan(int odrzan) {
        this.odrzan = odrzan;
    }




}


