package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String username;
     private int idModul;

    public Student() {
    }

    public Student(String username, int idModul) {
       this.username = username;
       this.idModul = idModul;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getIdModul() {
        return this.idModul;
    }
    
    public void setIdModul(int idModul) {
        this.idModul = idModul;
    }




}


