package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1



/**
 * StudentskaSluzba generated by hbm2java
 */
public class StudentskaSluzba  implements java.io.Serializable {


     private String username;
     private String telefon1;
     private String telefon2;

    public StudentskaSluzba() {
    }

	
    public StudentskaSluzba(String username, String telefon1) {
        this.username = username;
        this.telefon1 = telefon1;
    }
    public StudentskaSluzba(String username, String telefon1, String telefon2) {
       this.username = username;
       this.telefon1 = telefon1;
       this.telefon2 = telefon2;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getTelefon1() {
        return this.telefon1;
    }
    
    public void setTelefon1(String telefon1) {
        this.telefon1 = telefon1;
    }
    public String getTelefon2() {
        return this.telefon2;
    }
    
    public void setTelefon2(String telefon2) {
        this.telefon2 = telefon2;
    }




}


