package beans;
// Generated Sep 12, 2021 10:30:56 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VerzijaPrijave generated by hbm2java
 */
public class VerzijaPrijave  implements java.io.Serializable {


     private Integer idVer;
     private int idPrijava;
     private Date datumVer;
     private Date vremeVer;
     private String idStudent;
     private String idMentor;
     private String idMentorZ;
     private String idRukovodilac;
     private int idRad;
     private String nazivS;
     private String nazivE;
     private String predmet;
     private String sadrzaj;
     private Integer idPredmet;
     private int rukIliProf;
     private String biografija;
     private String idRukRada;
     private String idKom1;
     private String idKom2;
     private Date datum;
     private Integer prihvata;
     private String sugestija;
     private Date datumS;
     private String predsednikKomisije;

    public VerzijaPrijave() {
    }

	
    public VerzijaPrijave(int idPrijava, Date datumVer, Date vremeVer, String idStudent, String idMentor, String idRukovodilac, int idRad, String nazivS, String nazivE, int rukIliProf) {
        this.idPrijava = idPrijava;
        this.datumVer = datumVer;
        this.vremeVer = vremeVer;
        this.idStudent = idStudent;
        this.idMentor = idMentor;
        this.idRukovodilac = idRukovodilac;
        this.idRad = idRad;
        this.nazivS = nazivS;
        this.nazivE = nazivE;
        this.rukIliProf = rukIliProf;
    }
    public VerzijaPrijave(int idPrijava, Date datumVer, Date vremeVer, String idStudent, String idMentor, String idMentorZ, String idRukovodilac, int idRad, String nazivS, String nazivE, String predmet, String sadrzaj, Integer idPredmet, int rukIliProf, String biografija, String idRukRada, String idKom1, String idKom2, Date datum, Integer prihvata, String sugestija, Date datumS, String predsednikKomisije) {
       this.idPrijava = idPrijava;
       this.datumVer = datumVer;
       this.vremeVer = vremeVer;
       this.idStudent = idStudent;
       this.idMentor = idMentor;
       this.idMentorZ = idMentorZ;
       this.idRukovodilac = idRukovodilac;
       this.idRad = idRad;
       this.nazivS = nazivS;
       this.nazivE = nazivE;
       this.predmet = predmet;
       this.sadrzaj = sadrzaj;
       this.idPredmet = idPredmet;
       this.rukIliProf = rukIliProf;
       this.biografija = biografija;
       this.idRukRada = idRukRada;
       this.idKom1 = idKom1;
       this.idKom2 = idKom2;
       this.datum = datum;
       this.prihvata = prihvata;
       this.sugestija = sugestija;
       this.datumS = datumS;
       this.predsednikKomisije = predsednikKomisije;
    }
   
    public Integer getIdVer() {
        return this.idVer;
    }
    
    public void setIdVer(Integer idVer) {
        this.idVer = idVer;
    }
    public int getIdPrijava() {
        return this.idPrijava;
    }
    
    public void setIdPrijava(int idPrijava) {
        this.idPrijava = idPrijava;
    }
    public Date getDatumVer() {
        return this.datumVer;
    }
    
    public void setDatumVer(Date datumVer) {
        this.datumVer = datumVer;
    }
    public Date getVremeVer() {
        return this.vremeVer;
    }
    
    public void setVremeVer(Date vremeVer) {
        this.vremeVer = vremeVer;
    }
    public String getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(String idStudent) {
        this.idStudent = idStudent;
    }
    public String getIdMentor() {
        return this.idMentor;
    }
    
    public void setIdMentor(String idMentor) {
        this.idMentor = idMentor;
    }
    public String getIdMentorZ() {
        return this.idMentorZ;
    }
    
    public void setIdMentorZ(String idMentorZ) {
        this.idMentorZ = idMentorZ;
    }
    public String getIdRukovodilac() {
        return this.idRukovodilac;
    }
    
    public void setIdRukovodilac(String idRukovodilac) {
        this.idRukovodilac = idRukovodilac;
    }
    public int getIdRad() {
        return this.idRad;
    }
    
    public void setIdRad(int idRad) {
        this.idRad = idRad;
    }
    public String getNazivS() {
        return this.nazivS;
    }
    
    public void setNazivS(String nazivS) {
        this.nazivS = nazivS;
    }
    public String getNazivE() {
        return this.nazivE;
    }
    
    public void setNazivE(String nazivE) {
        this.nazivE = nazivE;
    }
    public String getPredmet() {
        return this.predmet;
    }
    
    public void setPredmet(String predmet) {
        this.predmet = predmet;
    }
    public String getSadrzaj() {
        return this.sadrzaj;
    }
    
    public void setSadrzaj(String sadrzaj) {
        this.sadrzaj = sadrzaj;
    }
    public Integer getIdPredmet() {
        return this.idPredmet;
    }
    
    public void setIdPredmet(Integer idPredmet) {
        this.idPredmet = idPredmet;
    }
    public int getRukIliProf() {
        return this.rukIliProf;
    }
    
    public void setRukIliProf(int rukIliProf) {
        this.rukIliProf = rukIliProf;
    }
    public String getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(String biografija) {
        this.biografija = biografija;
    }
    public String getIdRukRada() {
        return this.idRukRada;
    }
    
    public void setIdRukRada(String idRukRada) {
        this.idRukRada = idRukRada;
    }
    public String getIdKom1() {
        return this.idKom1;
    }
    
    public void setIdKom1(String idKom1) {
        this.idKom1 = idKom1;
    }
    public String getIdKom2() {
        return this.idKom2;
    }
    
    public void setIdKom2(String idKom2) {
        this.idKom2 = idKom2;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Integer getPrihvata() {
        return this.prihvata;
    }
    
    public void setPrihvata(Integer prihvata) {
        this.prihvata = prihvata;
    }
    public String getSugestija() {
        return this.sugestija;
    }
    
    public void setSugestija(String sugestija) {
        this.sugestija = sugestija;
    }
    public Date getDatumS() {
        return this.datumS;
    }
    
    public void setDatumS(Date datumS) {
        this.datumS = datumS;
    }
    public String getPredsednikKomisije() {
        return this.predsednikKomisije;
    }
    
    public void setPredsednikKomisije(String predsednikKomisije) {
        this.predsednikKomisije = predsednikKomisije;
    }




}


